// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Multi_Label_Classification
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(4)]
        public string Label { get; set; }


        [ColumnName("Sepal length"), LoadColumn(0)]
        public float Sepal_length { get; set; }


        [ColumnName("Sepal width"), LoadColumn(1)]
        public float Sepal_width { get; set; }


        [ColumnName("Petal length"), LoadColumn(2)]
        public float Petal_length { get; set; }


        [ColumnName("Petal width"), LoadColumn(3)]
        public float Petal_width { get; set; }


    }
}
